version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - REPOSITORY_URI=985988196667.dkr.ecr.ap-northeast-1.amazonaws.com/tsukaby-blog
      - VERSION=$(git rev-parse HEAD)
      - EB_FILE_NAME=${VERSION}.zip
  build:
    commands:
      - docker build -t ${REPOSITORY_URI}:${VERSION} .
      - cd eb
      - envsubst < Dockerrun.aws.tmpl.json > Dockerrun.aws.json
      - zip -r ../${EB_FILE_NAME} ./
      - cd ..
  post_build:
    commands:
      - docker push ${REPOSITORY_URI}:${VERSION}
      - aws s3 mv ${EB_FILE_NAME} s3://tsukaby-eb-binary/tsukaby-blog/
      - |
        aws elasticbeanstalk delete-application-version \
          --application-name tsukaby-blog --version-label ${VERSION} \
          --region ap-northeast-1
      - |
        aws elasticbeanstalk create-application-version \
          --application-name tsukaby-blog --version-label ${VERSION} \
          --source-bundle S3Bucket="tsukaby-eb-binary",S3Key=tsukaby-blog/${EB_FILE_NAME} \
          --region ap-northeast-1
